name = "Daily Comic"
license = "MIT"
licenselink = "https://github.com/uatthaphon/dailycomic/blob/master/LICENSE.md"
description = "Simple theme for daily comic."
homepage = "https://gitlab.com/uatthaphon/dailycomic"
tags = ["blog", "comic"]
features = ["blog", "comic"]
min_version = "0.30.2"

[author]
  name = "Atthaphon Urairat"
  homepage = "https://gitlab.com/uatthaphon/dailycomic"
