baseURL = "http://example.org/"
languageCode = "en-us"
title = "Daily Comic"

theme = "dailycomic"

[author]
    name = "Someone"
    email = "someone@gmail.com"
[params]
    sitename = "Daily Comic"

[permalinks]
    archive = ":title"

[[params.social]]
    name = "Github"
    icon = "fab fa-github color-github"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook color-facebook"
    weight = 2
    url = "https://www.facebook.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter color-twitter"
    weight = 3
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin color-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium color-medium"
    weight = 5
    url = "https://medium.com/@johndoe"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss-square color-rss"
    weight = 5
    url = "/index.xml"
